#!/bin/bash

# sudo mode
sudo -s

# This script's directory
SCRIPT=$(readlink -f "$0")
THISDIR=$(dirname "$SCRIPT")

# install requirements
apt-get install -y $(cat reqs.txt)

# update dhcpd to ignore wlan0
echo "denyinterfaces wlan0" >> /etc/dhcpcd.conf

# rename original interfaces and replace with wlan static IP conf
mv /etc/network/interfaces /etc/network/interfaces.orig
cp $THISDIR/interfaces -d /etc/network/interfaces

# restart dhcpcd and reload wlan0 configuration
service dhcpcd restart
ifdown wlan0; ifup wlan0

# copy new hostapd configuration
cp $THISDIR/hostapd.conf -d /etc/hostapd/hostapd.conf

# update hostapd defaults with configuration path
sed -i '/#DAEMON_CONF=/c\DAEMON_CONF="/etc/hostapd/hostapd.conf"' /etc/default/hostapd

# rename original dnsmasq.conf and replace with ours
mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
cp $THISDIR/dnsmasq.conf -d /etc/dnsmasq.conf

# enable ip forwarding
sed -i '/#net\.ipv4\.ip_forward=1/c\net.ipv4.ip_forward=1' /etc/sysctl.conf
sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

# configure nat between wlan0 and eth0
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
sh -c "iptables-save > /etc/iptables.ipv4.nat"
sed -i '/exit 0/i iptables-restore < /etc/iptables.ipv4.nat' /etc/rc.local

# start services
service hostapd start
service dnsmasq start

# exit sudo mode
exit
