#!/bin/bash

# this script's directory
SCRIPT=$(readlink -f "$0")
THISDIR=$(dirname "$SCRIPT")
DWNLDDIR=$THISDIR/tmp

# update/upgrade
sudo apt-get update -y
sudo apt-get upgrade -y

# install dependencies
sudo apt-get install -y $(cat reqs.txt)

# create tmp directory
mkdir $DWNLDDIR

# Download binary release into DWNLD_DIR
curl -o $DWNLDDIR/bro-2.5.tar.gz  https://www.bro.org/downloads/bro-2.5.tar.gz

# Unpack the bro tarball
tar -xvzf $DWNLDDIR/bro-2.5.tar.gz --directory $DWNLDDIR/

# CMMI bro
cd $DWNLDDIR/bro-2.5 && \
    ./configure && \
    make && \
    sudo make install

# remove tmp directory
sudo rm -rf $DWNLDDIR

# add path globally
sudo su -c 'echo "export PATH=/usr/local/bro/bin:$PATH" >> /etc/bash.bashrc'

